
version: '2'
services:
  mongodb:
    container_name: payments-api-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=payments
    ports:
        - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb