version: '2'
services:

  mongodb:
    image: mongo:3.6.3
    container_name: payments-mongo
    environment:
      - MONGO_DATA_DIR=./data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=payments
    ports: 
      - "27017:27017"

  app:
    container_name: payments-app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - "8081:8081"
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    command: mvn clean spring-boot:run
